### ISSUE TITLE
[Feature Request] Atmos downloading

### ISSUE THREAD

**Issue by florinsdistortedvision** [QiuChenly/QQFlacMusicDownloader#10]
As the tile suggests, add support for Dolby Atmos (m4a) tracks from QQ

![image](https://user-images.githubusercontent.com/97384306/187181744-984ac429-bce5-4cd7-aec8-e6319636e3c9.jpeg)

**Comment by QiuChenly** [comment]
You can use that 'Hi-Res' (flac) music sources, Dolbe Atmos type are not support now.
If you means '*.m4a' music type file, the code can fetch and donwload it:

```python
        elif int(id['size_96aac']) != 0:
            code = "C400"
            format = "m4a"
            qStr = "低品质 96kbps"
            fsize = int(id['size_96aac'])
```

But that so low-Res music ,and  low than mp3., just 96kbps...
:(

**Comment by florinsdistortedvision** [comment]
Thank you, tho yes I do mean Dolby Atmos support (which is usually in a .m4a encoder). I am aware of the AAC option for low-res music.
