### ISSUE TITLE
8.136.185.193这个ip似乎已经不能用了，需要更新一下

### ISSUE THREAD

**Issue by ppsoft1986** [QiuChenly/QQFlacMusicDownloader#11]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='8.136.185.193', port=80):

**Comment by yinhui1984** [comment]
post 到 http://8.136.185.193/api/Cookies 返回502, 大佬搞一搞这个问题, 现在用不了了,好可惜

**Comment by LeoMei** [comment]
我也是遇到这个问题，大佬有空的时候看看能不能补救

**Comment by ppsoft1986** [comment]
散了吧https://github.com/OJZen/QMD_Android

**Comment by QiuChenly** [comment]
本项目已复活 能撑多久看网友的逆天程度
