### ISSUE TITLE
为什么网易云点开后404？

### ISSUE THREAD

**Issue by Sjey-Lyn** [QiuChenly/QQFlacMusicDownloader#12]
![image](https://user-images.githubusercontent.com/74102271/222938248-0010759b-7a50-4ba7-b227-d92c948c7a3c.png)
1. 为什么网易云点开后404？
2. main.py直接运行会报错？

**Comment by QiuChenly** [comment]
1.因为重构代码后前端UI还未设计完成
2.因为重构代码后直接运行MainServer即可 main.py下个版本将被彻底移除

**Comment by Sjey-Lyn** [comment]
那里面的api能正常使用吗？比如下载网易云歌单？

**Comment by QiuChenly** [comment]
可以 下个版本会重新适配网易云

**Comment by Sjey-Lyn** [comment]
好的，谢谢
