### ISSUE TITLE
解析失败？

### ISSUE THREAD

**Issue by Sjey-Lyn** [QiuChenly/QQFlacMusicDownloader#13]
![image](https://user-images.githubusercontent.com/74102271/222944389-1410296a-432b-4cb8-9986-f46a298828a0.png)
早上用了一下，下午突然不能用了？

**Comment by QiuChenly** [comment]
第三方解析接口服务器似乎因为脚本请求的缘故 会时不时崩溃 等一会儿就正常了

**Comment by Sjey-Lyn** [comment]
一天过去了，还是解析失败

**Comment by QiuChenly** [comment]
更新项目 可以使用酷我接口
