### ISSUE TITLE
运行后退出是怎么回事

### ISSUE THREAD

**Issue by agcboy** [QiuChenly/QQFlacMusicDownloader#14]
为什么我跑到这里就会自动退出，也不报错。上午的版本还可以启动网站，这个直接不可以了。
之前main.py版本就是这个问题，昨晚你改为网页版没调用网易这个方法所以可以，现在最新更新的这版启动网站前调用这个方法又报错了？我该怎么处理能获取网易云歌单？

![image](https://user-images.githubusercontent.com/5435462/222947745-696328ec-1d3a-47f9-add4-e512de39ce62.png)

**Comment by QiuChenly** [comment]
请使用MainServer.py

**Comment by agcboy** [comment]
> 是用MainServer.py，注释掉图中新增的这两段就能启动，不注释还是会调用第一个截图的地方，然后就停掉了。

![image](https://user-images.githubusercontent.com/5435462/222956791-a7dd54e6-20fd-44bb-ab2f-750f09defa1b.png)

**Comment by QiuChenly** [comment]
谢谢，已解决此问题。
这是由于IDE自动排序import导致的 实际上应该按顺序加载三个模块
分别是

# 由于Python解释性语言特性，必须要严格按照加载顺序

from web.App import Start  # 必须先加载他 这是初始化flask框架代码
from web.API.es import init as es  # 下面无需顺序
from web.API.qq import init as qq  # es qq模块不分顺序

es()  # 加载API接口
qq()

Start()  # 最后启动总函数
