### ISSUE TITLE
怎么绑定cookie？

### ISSUE THREAD

**Issue by railannad** [QiuChenly/QQFlacMusicDownloader#15]
搜了个歌，单独下载都返回403。 本地搜了一下，没发现config文件，  怎么绑定cookie的啊大佬

**Comment by QiuChenly** [comment]
请使用酷我音乐 GUI版本在重构中暂时无法给QQ音乐单独设置Cookie

**Comment by railannad** [comment]
> 请使用酷我音乐接口 GUI版本在重构中暂时无法给QQ音乐单独设置Cookie

然后发现酷我音乐没有音质信息（
感谢大佬，期待后续更新

**Comment by QiuChenly** [comment]
是这样的 我直接强制下载flac音质 并且酷我服务器竟然不在返回json里标注支持什么类型的音质 蚌埠住了 只好全部用flac下载

**Comment by zhwaiting** [comment]
![image](https://user-images.githubusercontent.com/4969818/224869319-c1bc63ed-cdce-455a-9e68-46b0f818d5e6.png)
一首越南歌曲下不下来，字符集貌似出问题了。

**Comment by QiuChenly** [comment]
> ![image](https://user-images.githubusercontent.com/4969818/224869319-c1bc63ed-cdce-455a-9e68-46b0f818d5e6.png) 一首越南歌曲下不下来，字符集貌似出问题了。

Windows上的unicode编码问题引起的。
如果有条件可以提Pull Requests.

**Comment by tomzh0u** [comment]
> > ![image](https://user-images.githubusercontent.com/4969818/224869319-c1bc63ed-cdce-455a-9e68-46b0f818d5e6.png) 一首越南歌曲下不下来，字符集貌似出问题了。
> 
> Windows上的unicode编码问题引起的。 如果有条件可以提Pull Requests.

算了，还是改Windows编码最方便
![image](https://user-images.githubusercontent.com/4969818/224938468-8bc5848d-52c1-4076-b912-63fab6220c97.png)

**Comment by heisajoker** [comment]
能否部署私网，然后下载保存本地

**Comment by QiuChenly** [comment]
> 能否部署私网，然后下载保存本地

可以内网绑定SSL和DNS解析 数据保留在服务器

**Comment by heisajoker** [comment]
有事留下姓名！

**Comment by heisajoker** [comment]
有事留下姓名！
