### ISSUE TITLE
运行MainServer.py之后，chrome打不开web界面，提示ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by pingko-WI** [QiuChenly/QQFlacMusicDownloader#16]
我的电脑是Windows 10，安装了官网最新的python。然后按着您的说明一步一步操作，都成功了，没有报错。
到了最后的这一步：执行python3 MainServer.py命令（回车后cmd窗口无任何反馈），chrome浏览器访问 http://localhost:8899/ ，会提示“localhost 拒绝了我们的连接请求 ERR_CONNECTION_REFUSED”。请问这是怎么回事

**Comment by QiuChenly** [comment]
有截图吗
最好带上详细操作步骤

**Comment by agcboy** [comment]
> 我的电脑是Windows 10，安装了官网最新的python。然后按着您的说明一步一步操作，都成功了，没有报错。 到了最后的这一步：执行python3 MainServer.py命令（回车后cmd窗口无任何反馈），chrome浏览器访问 http://localhost:8899/ ，会提示“localhost 拒绝了我们的连接请求 ERR_CONNECTION_REFUSED”。请问这是怎么回事


按图修改下就好了
![image](https://user-images.githubusercontent.com/5435462/223022690-e73e2170-9a7f-4a86-a027-c86bf28d1a9d.png)

**Comment by QiuChenly** [comment]
> > 我的电脑是Windows 10，安装了官网最新的python。然后按着您的说明一步一步操作，都成功了，没有报错。 到了最后的这一步：执行python3 MainServer.py命令（回车后cmd窗口无任何反馈），chrome浏览器访问 http://localhost:8899/ ，会提示“localhost 拒绝了我们的连接请求 ERR_CONNECTION_REFUSED”。请问这是怎么回事
> 
> 按图修改下就好了 ![image](https://user-images.githubusercontent.com/5435462/223022690-e73e2170-9a7f-4a86-a027-c86bf28d1a9d.png)

谢谢指正，已删除cv2引用错误
