### ISSUE TITLE
以一种访问权限不允许的方式做了一个访问套接字的尝试

### ISSUE THREAD

**Issue by DarrenSong** [QiuChenly/QQFlacMusicDownloader#17]
PS D:\Github\QQFlacMusicDownloader> python.exe .\MainServer.py
kw_token已生成 GWD5PD3QZE4
 * Serving Flask app 'web.App'
 * Debug mode: off
以一种访问权限不允许的方式做了一个访问套接字的尝试。

**Comment by QiuChenly** [comment]
也许你没有允许python创建服务器
Windows上的网络设置权限问题
