### ISSUE TITLE
运行MainServer 后 浏览器访问出现 302 与 304 错误

### ISSUE THREAD

**Issue by QingXuDw** [QiuChenly/QQFlacMusicDownloader#18]
问题：
运行MainServer 后 浏览器访问http://127.0.0.1:8899， 命令行窗口出现 302 与 304 错误， 浏览器成功跳转至index.html但没有正常页面显示。
![image](https://user-images.githubusercontent.com/49812095/223938187-f7006df6-3927-4b36-860f-f274e746a469.png)

环境：
* Windows10 22H2
* Python3.10
* Chrome 110.0.5481

复现方法：
clone本项目后在根目录运行以下指令
```cmd
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
pip install -r requirements.txt
python MainServer.py
```
在chrome中访问http://127.0.0.1:8899

运行结果
![image](https://user-images.githubusercontent.com/49812095/223937281-0d8a1576-f7f9-47bf-889e-a80323e2651b.png)

**Comment by QiuChenly** [comment]
不清楚为什么会出现这种问题 可以+q看下问题

**Comment by QingXuDw** [comment]
加你了

**Comment by QingXuDw** [comment]
问题已在 [Commit 9aa1e5](https://github.com/QiuChenly/QQFlacMusicDownloader/commit/9aa1e5c82858f91c37cfb3eb1547e92d952a4bbb) 中解决，感谢开发者的工作。
