### ISSUE TITLE
qq音乐搜索bug

### ISSUE THREAD

**Issue by Mrzqd** [QiuChenly/QQFlacMusicDownloader#21]
搜索qq音乐时候前端会多提交一个size，然后后端就报错404，在路由添加size后搜索不到音乐
![image](https://user-images.githubusercontent.com/104408988/224218186-0d4e5cab-53d2-4c97-be91-f74619384b00.png)
![image](https://user-images.githubusercontent.com/104408988/224218264-97ac23d3-3e3d-45f2-9b02-90d8c9d3afa0.png)

**Comment by QiuChenly** [comment]
已确认问题。
1.关于404，已经合并了这个错误并对齐进行了修复，这是由于上一次提交的改动破坏了设计。
2.搜索不到音乐是因为搜索接口需要用户cookie信息才能无限制搜索，否则有时候会搜索不到歌曲，返回空列表。目前后端暂未配置用户cookie搜索。

感谢你的反馈，已经在代码中提交了本次确认的问题的修复代码。
