### ISSUE TITLE
在腾讯云linux上运行后 远程访问，发现网易云不能扫码登陆

### ISSUE THREAD

**Issue by xztxy** [QiuChenly/QQFlacMusicDownloader#23]
在腾讯云linux上运行后 远程访问，发现网易云不能扫码登陆.，请问下除了8899是否有其他端口需要放行。

**Comment by QiuChenly** [comment]
请不要直接暴露实际IP地址到外网，使用宝塔或者自行配置Nginx转发443配置ssl到本地localhost。

**Comment by QiuChenly** [comment]
这是正常访问了
如果你还有其他问题可以加我q 1925374620给你检查看看服务器
