### ISSUE TITLE
运行后正常，但是chrome打开localhost后内容空白，网页标题显示我的乐库

### ISSUE THREAD

**Issue by ues1024** [QiuChenly/QQFlacMusicDownloader#26]
如题，一般什么问题造成的啊？谢谢

**Comment by QiuChenly** [comment]
1.更新代码。
2.操作步骤 环境 图

**Comment by ues1024** [comment]
更新的最新代码，用的pycharm2022.1社区版，python版本是3.11.2
步骤是先github更新最新代码、接着pip3 install -r .\requirements.txt安装库、然后运行python .\MainServer.py
![20230313154717](https://user-images.githubusercontent.com/94524879/224644068-346a7cf0-dac7-4ced-b7e5-d66a82b3c481.jpg)
![20230313154905](https://user-images.githubusercontent.com/94524879/224644224-1fdb0699-1082-494e-8dd0-fb7e6adca2a8.jpg)

**Comment by QiuChenly** [comment]
目前不知道是什么原因引起。可能是加载数据出了问题。
可以联系我q检查问题所在。1925374620
