### ISSUE TITLE
部分标题带“版”字的歌曲搜索不到

### ISSUE THREAD

**Issue by ClareDuan** [QiuChenly/QQFlacMusicDownloader#32]
main.py里面的
filterList = params.get('filterList',
                            ['DJ', 'Remix', '即兴', '变调', 'Live', '伴奏', '版,', '版)', '慢四', "纯音乐", '二胡',
                             '串烧', '现场'])
使得搜索结果里带“版”字的歌曲都被过滤了，但是有些歌曲并不是现场版或DJ版，而是完整版、新版、重录版之类的，也被一并过滤掉了，filterList这一段删了也没用

**Comment by QiuChenly** [comment]
给出样例并详细说明

**Comment by ClareDuan** [comment]
样例:https://y.qq.com/n/ryqq/albumDetail/002xkac41w9BpJ
按照 b:002xkac41w9BpJ 高级搜索时，提示 过滤后没有发现符合条件的数据。

**Comment by QiuChenly** [comment]
1. 这个不是问题，是为了过滤歌曲质量。在设计之初我并没有听DJ版/现场版/翻唱版的需求。
2. 问题已经通过增加新功能解决：https://github.com/QiuChenly/QQFlacMusicDownloader/commit/d4b0bc0fff79791da4ce4433ff886c8a28693f7d
