### ISSUE TITLE
进入网页端提示点击保存按钮，无法进入下载界面

### ISSUE THREAD

**Issue by housa000** [QiuChenly/QQFlacMusicDownloader#36]

**Comment by QiuChenly** [comment]
什么意思？图 还有把问题描述清楚，你描述的和你以为你描述的不是同一个意思

**Comment by housa000** [comment]
![屏幕截图 2023-04-24 090402](https://user-images.githubusercontent.com/125365102/233878020-daee1430-a883-4f7e-85f0-f8a1303a2ea0.png)

![屏幕截图 2023-04-24 090528](https://user-images.githubusercontent.com/125365102/233877995-eeb4be65-12c2-403a-9f4b-7321f13cb532.png)
运行完程序，打开网页，出现这个界面后，点击保存没有反应

**Comment by QiuChenly** [comment]
点击保存就不会提示任何信息。
而下载界面是通过左侧菜单栏进入的，看起来css样式出了问题，可以尝试重新换一个浏览器打开试试，如果还是无法看到侧边栏请截图跟帖说明。

**Comment by housa000** [comment]
换了浏览器可以显示侧边栏，我现在使用的edge，之前网页可以正常显示，后来就不行了，应该怎么处理？

**Comment by QiuChenly** [comment]
对于你说的“之前可以显示后来就不行了”这个问题我无法理解实际情况，因为我没有收到关于css样式加载出错的bug提交，请在页面按下f12打开开发者工具复现问题后观察控制台并截图描述详细细节提交给我。
