### ISSUE TITLE
终端无限请求‘等待扫码’进程

### ISSUE THREAD

**Issue by wayner6** [QiuChenly/QQFlacMusicDownloader#37]
我正在下载qq音乐的歌单，一切正常速度也很快，跑满了我的带宽  
无意间点了一些前端的网易云音乐登录，需要扫码，这时切换到音乐搜索界面之后查看终端进程，发现它还在请求扫码登录，迫于无奈，我扫码登录，但是我扫码登录以后终端还是在请求二维码，对功能没什么影响，只是想反馈一下这个bug
![image](https://user-images.githubusercontent.com/88063517/234301144-7ef44b00-4775-47a5-b352-e3e8a93696fa.png)

**Comment by QiuChenly** [comment]
这是前端的一个逻辑bug.但这个问题应该已经在某次提交中更新修复，请同步最新的代码尝试解决此问题。并且该问题只是因为点进了网易云登录页，实际上直接刷新前端页面即可。

**Comment by wayner6** [comment]
@QiuChenly 明白，感谢🥰
