### ISSUE TITLE
第一次能打开下载，后面就拒绝访问

### ISSUE THREAD

**Issue by Theearthquake** [QiuChenly/QQFlacMusicDownloader#39]
老哥请问一下为啥我配好之后，进去下了首歌后，退出重进就拒绝访问了，求助~
![屏幕截图 2023-04-27 171218](https://user-images.githubusercontent.com/131959906/234816526-8b68fdad-0bc4-4ea3-8792-0a7ca241aabe.png)

**Comment by QiuChenly** [comment]
不要关闭python后端服务 谢谢

**Comment by Theearthquake** [comment]
原来我一退出cmd就自动断开python后端了，感谢老哥解答！
