### ISSUE TITLE
有没有什么方法可以查看下载进度

### ISSUE THREAD

**Issue by lancer-wang** [QiuChenly/QQFlacMusicDownloader#40]
不知道是不是卡住了
![image](https://user-images.githubusercontent.com/69783837/234822280-64088c8f-e8da-4653-b669-3fd7db27e891.png)

去下载目录看，是有很多歌没下的

**Comment by QiuChenly** [comment]
并发有限制 在主页修改并发数量 他是按照顺序下载的 只要看自己电脑流量是不是满带宽在跑就知道了

**Comment by lancer-wang** [comment]
> 并发有限制 在主页修改并发数量 他是按照顺序下载的 只要看自己电脑流量是不是满带宽在跑就知道了

0.0 我是看有的歌只下了歌词
![image](https://user-images.githubusercontent.com/69783837/235037265-a85976ba-45a8-446e-9c14-d3b5311996e1.png)

有的歌点了下载，然后目录里面很久也没出现

**Comment by lancer-wang** [comment]
非常诡异，我把这个歌曲的目录删掉，然后点下载，这次连目录都没出现
但是我把下载目录给删掉之后，批量下载整页，突然就下载成功了
![image](https://user-images.githubusercontent.com/69783837/235037933-e7deac53-b4bf-4dca-a220-f9d06ebd0671.png)
