### ISSUE TITLE
docker部署那边最好把挂载目录加上吧

### ISSUE THREAD

**Issue by lancer-wang** [QiuChenly/QQFlacMusicDownloader#43]
`docker run -p 127.0.0.1:8899:8899 -v 本地目录:/workspace/music -it dockerimage:latest `
docker-compose的是
```
volumes:
   - 本地目录:/workspace/music
```

**Comment by lancer-wang** [comment]
这个是我自己docker-compose.yml
version: "3"
services:
  downloader:
    image: registry.cn-hangzhou.aliyuncs.com/music_downloader/qq_flac_music_downloader
    container_name: music
    network_mode: bridge
    volumes:
      - /coptyo/musics:/workspace/music
    ports:
      - "127.0.0.1:62253:8899"
    restart: always

**Comment by QiuChenly** [comment]
感谢你的issues, 如果方便的话请将此patch合并入yml文件并更新readme部分
