### ISSUE TITLE
提示已提交但是下载列表没有

### ISSUE THREAD

**Issue by code-jar** [QiuChenly/QQFlacMusicDownloader#48]
QQ音乐源下载无损音乐，点击下载提示提交任务成功，但是下载列表没有。
当前docker部署，只映射了本地文件夹没改动其他任何配置
docker日志只看到了请求日志，没有其他异常日志

**Comment by QiuChenly** [comment]
下载列表功能没做

**Comment by code-jar** [comment]
之前是下载文件夹里都没有文件，不知道什么原因，容器重启了下就好了
