### ISSUE TITLE
Windows下关于几个个bug的修改

### ISSUE THREAD

**Issue by a274646204** [QiuChenly/QQFlacMusicDownloader#5]
windows下将以下代码：

    localFile = f"{it['singer']} - {it['title']}.{it['extra']}".replace(
        "/", "\\")
    localLrcFile = f"{it['singer']} - {it['title']}.lrc".replace(
        "/", "\\")
    mShower = localFile
    my_path = download_home+it['singer']+'/'
    if not onlyShowSingerSelfSongs:
        if not os.path.exists(my_path):
            os.mkdir(f"{my_path}")
    my_path = f"{my_path}{it['album']}"
    if not os.path.exists(my_path):
        os.mkdir(f"{my_path}")
    localFile = os.path.join(my_path, f"{localFile}")
    localLrcFile = os.path.join(my_path, f"{localLrcFile}")

替换为：

    localFile = f"{it['singer']} - {it['title']}.{it['extra']}".replace(
        "/", ",")
    localLrcFile = f"{it['singer']} - {it['title']}.lrc".replace(
        "/", ",")
    localFile = localFile.replace('|','')
    localLrcFile=localLrcFile.replace('|','')
    mShower = localFile
    my_path = download_home+it['singer']+'\\'
    my_path = my_path.replace('"','')
    my_path = my_path.replace("'",'')
    my_path = my_path.replace('|','')
    my_path = my_path.replace('*','')
    my_path = my_path.replace('?','')
    my_path = my_path.replace('<','')
    my_path = my_path.replace('>','')
    my_path = my_path.replace('/', '-')
    if not onlyShowSingerSelfSongs:
        if not os.path.exists(my_path):
            os.mkdir(f"{my_path}")
    my_path = f"{my_path}{it['album']}"
    my_path = my_path.replace('"','')
    my_path = my_path.replace("'",'')
    my_path = my_path.replace('|','')
    my_path = my_path.replace('*','')
    my_path = my_path.replace('?','')
    my_path = my_path.replace('<','')
    my_path = my_path.replace('>','')
    my_path = my_path.replace('.', '')
    my_path = my_path.replace('/', '-')
    if not os.path.exists(my_path):
        os.mkdir(f"{my_path}")
    localFile = os.path.join(my_path, f"{localFile}")
    localLrcFile = os.path.join(my_path, f"{localLrcFile}")
解决一些歌曲无法下载的问题

**Comment by QiuChenly** [comment]
谢谢你的反馈.
但是若按照你的修改方法，会存在以下问题：
my_path = my_path.replace('/', '-') # 本代码若将其全部替换为-，意味着如下：C:/aa/aa/aas/as - sa.flac将会变为C:-aa-aa-aas-as - sa.flac，此路径为非法路径。
if not onlyShowSingerSelfSongs:
    if not os.path.exists(my_path):
        os.mkdir(f"{my_path}") # 在这里创建路径是非法路径：C:-aa-aa-aas-as - sa.flac

如果你的意思是
my_path = download_home+it['singer']+'\\'
歌曲的名称中出现了非法字符：如“<>/?.”等，可以就以下两个值进行处理
1   {it['singer']}
2  {it['title']}

代码片段 函数 def parseList(list, target):
     .....
songs.append({
            'prefix': code,
            'extra': format,
            'notice': qStr,
            'mid': mid,
            'songmid': i['mid'],
            'size': fsize,
            'title': f'{i["title"]}', # 此处对歌曲名称做处理
            'singer': f'{singer}', # 此处对歌手名称做处理
            'album': albumName}) # 此处对专辑名称做处理
位于代码346行处。

**Comment by QiuChenly** [comment]
有关此问题，我将会在近期修复，谢谢你的测试，如果有提供样本音乐文件供测试就更好了🤓🤓🤓
