### ISSUE TITLE
QQ音乐杜比全景声？

### ISSUE THREAD

**Issue by Andrea-lyz** [QiuChenly/QQFlacMusicDownloader#54]
据我所知目前只有apple music（自家设备）和QQ音乐（安卓端）提供了真正的5.1以上的多声道的设备端的杜比全景声文件
像国外Tidal Amazon之类的平台都是云端双耳渲染再下发到设备端，所以一些空间音频设备没法正确的识别到声道信息
请问一下是否有希望下载到QQ音乐杜比全景声文件呢？
![7a6b168bb481b497a5f40086af945af5](https://user-images.githubusercontent.com/52863141/236354336-27d8523a-b2cb-4c5b-82ec-cc91b349d05e.jpeg)

**Comment by QiuChenly** [comment]
暂时没有办法，因为接口也是来自第三方服务器，这方面可能很难拿到。
