### ISSUE TITLE
网页样式有问题

### ISSUE THREAD

**Issue by Carlos920** [QiuChenly/QQFlacMusicDownloader#55]
![image](https://user-images.githubusercontent.com/32257015/236368545-8f5367af-642d-404a-b911-f55aef0d5195.png)
看了下，是由于css的overflow写死为scroll导致的，改为auto后页面显示正常

![image](https://user-images.githubusercontent.com/32257015/236368674-153e4216-557f-4edc-be77-7c2946bd59be.png)

测试docker镜像
```shell
 docker run --name QQFlacMusicDownloader --rm -itd  -p 8899:8899 azraias/qq_flac_music_d
ownloader:latest
```

**Comment by QiuChenly** [comment]
谢谢你的反馈，如果方便可以直接提交fixup后的vue源码，review后我将会合并到主分支。
前端代码地址: https://github.com/QiuChenly/QQFlacMusicDownloader/blob/main/WebSourceCode
