### ISSUE TITLE
感觉下载了个寂寞

### ISSUE THREAD

**Issue by lalabg** [QiuChenly/QQFlacMusicDownloader#56]

**Comment by lalabg** [comment]
[img](https://i.postimg.cc/FsmbYVhw/QQ-20230506125200.png)
[img](https://i.postimg.cc/L6Cqmt5t/QQ-20230506125205.png)

看一起一切正常，到文件夹里面一看空空如也。。。

**Comment by QiuChenly** [comment]
有问题请贴出后台python的执行状态截图 还有你的具体操作方法 网速流量有没有跑满 路径是否存在
而不是用这种令人不爽的标题和不知所闻的截图和描述来反馈

为了严谨的反驳你，我自己重新打开项目下载了一次。

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/24793281/236602495-1e75d32f-6397-4e8d-84c7-59a5839d120f.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/24793281/236602524-f1318eca-be55-40a1-9ef5-b2ab4e101e19.png">
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/24793281/236602528-cdf8938c-bb55-4e05-8ad1-eb64d2f44e7b.png">

**Comment by lalabg** [comment]
反驳的漂亮，估计是我的问题，后台不跑数据，~！@#￥￥%
[](https://i.postimg.cc/QdQ6mFKw/QQ-20230506150100.png)

**Comment by lalabg** [comment]
[](https://i.postimg.cc/QdQ6mFKw/QQ-20230506150100.png)

**Comment by lalabg** [comment]
[下载成功.jpg](https://i.postimg.cc/W1JL0Brz/QQ-20230506165607.png)

WIN10正确路径写法 `volumes:      - /F/Downloads/MUSIC`
