### ISSUE TITLE
[BUG] Special characters break the tool /  特殊字符破坏工具

### ISSUE THREAD

**Issue by florinsdistortedvision** [QiuChenly/QQFlacMusicDownloader#6]
Hello, great tool. If track has special characters that cannot be added in Windows file names, like "  \ / : * ? " < > | " will break the ripper. Quick example try to grab What Do You Mean? (Remix) by Justin Bieber.

A fix would be that the ripper to exclude those characters. Thank you!

你好，很棒的工具。 如果 track 有不能添加到 Windows 文件名中的特殊字符，例如“\ / : * ?” < > | “将打破开膛手。快速示例尝试抓取 Justin Bieber 的 What Do You Mean? (Remix)。

解决方法是让开膛手排除这些字符。 谢谢！对不起中文不好，正在使用翻译:)

**Comment by QiuChenly** [comment]
thx u reply to me about this question,you're right.i will debug it and fixing the problem soon.
