### ISSUE TITLE
[Request] Download based on links / 根据链接下载

### ISSUE THREAD

**Issue by florinsdistortedvision** [QiuChenly/QQFlacMusicDownloader#8]
As the title suggests, add a option to download based on link (album or single). Search function works great, but this would make everything easier and faster to download whole albums instead of individual tracks.

Example of input:
Input letter "L" for link (similar to how "S" is search) > input link (ex: https://y.qq.com/n/ryqq/albumDetail/003qGXqG4WmYDA).

如标题所示，添加基于链接（专辑或单曲）下载的选项。 搜索功能效果很好，但这将使下载整个专辑而不是单个曲目的一切变得更容易和更快。

输入示例：
链接输入字母“L”（类似于搜索“S”的方式）>输入链接（例如：https://y.qq.com/n/ryqq/albumDetail/003qGXqG4WmYDA）。

再次抱歉翻译，我正在使用谷歌:)

**Comment by QiuChenly** [comment]
if you want download single matches music file,you can input this music's number  of  your search result(e.g. 1 or 99, it usually front of music 's title。

**Comment by florinsdistortedvision** [comment]
It's good for singles but for albums just dropping a link and automatically downloading all the songs would be easier than searching and inputting the numbers from that album.

**Comment by QiuChenly** [comment]
Sounds like a good idea.I will write some code to try to download album and single music from user-defined web link.thx for your suggestion.
