### ISSUE TITLE
可以下载歌单里的歌曲吗？

### ISSUE THREAD

**Issue by quchifanma** [QiuChenly/QQFlacMusicDownloader#9]
https://y.qq.com/n/ryqq/playlist/8476553848

类似这种别人整理好的歌曲，想全部下载下来，辛苦您啦，邱哥。

**Comment by QiuChenly** [comment]
目前还没找到解析歌单的接口 抓包的接口都是加密的 等找到解析接口就可以做了

**Comment by QiuChenly** [comment]
现在已经支持下载网易云我喜欢的音乐下载了

**Comment by quchifanma** [comment]
> 现在已经支持下载网易云我喜欢的音乐下载了

好的，谢谢您秋晨。
